name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Install dotnet-script
      run: dotnet tool install dotnet-script -g

    - name: Generate files
      run: dotnet script generate.csx

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update generated files

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --no-restore --verbosity normal
