name: Publish

on:
  workflow_dispatch:
  release:
    types:
    - published

env:
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v3

    - name: Fetch version
      run: |
        git fetch --prune --unshallow
        v=$(git describe --tags --abbrev=0 --match v[0-9]*.[0-9]*.[0-9]*)
        echo "Using version ${v:1}"
        echo "VERSION=${v:1}" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore

    - name: Install dotnet-script
      run: dotnet tool install dotnet-script -g

    - name: Pack
      run: dotnet pack ./SafeRouting.Generator -c Release -o ./artifacts /p:ContinuousIntegrationBuild=true -p:Version=${{ env.VERSION }}

    - name: Test NuGet package
      run: dotnet script nuget-test.csx -- ${{ env.VERSION }}

    - name: Push to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg -k ${{ secrets.NUGET_APIKEY }} -s ${{ env.NUGET_SOURCE_URL }}

